#This file analyses anonymized data provided by "loadAnonymiseSaveData.R" in exp-specific directory
#Working directory is set hopefully by Rproj file to directory that it's in.
setwd(
"/Users/alexh/Documents/attention_tempresltn/multiple object tracking/newTraj/newTraj_repo/analysis"
)
dataDir="../dataAnonymized/"
expName="offCenterAndShape"
anonDataFilename = paste(dataDir,expName,".Rdata",sep="") #generated by loadAnonymiseSaveData.R
load(anonDataFilename,verbose=TRUE)  #returns dat
excludeFixationViolations = TRUE; proportnTrialsMustFixate = .6
excludeDidntReach75pct = TRUE
useQuickpsy = TRUE
if (useQuickpsy) {
  library(devtools) #So can load from Alex's local quickpsy package repository
  #install_github('danilinares/quickpsy')
  load_all("/Users/alexh/Documents/softwareStatsEquipment/programming_psychophysics/quickpsy/quickpsy")
  #library('quickpsy')
}
datWithFixatnViolatns = dat #save for possible future use
if (excludeFixationViolations) {
  bySubjExp <- dat %>% group_by(subject,exp)
  pOutCentralArea <- summarise(bySubjExp, pOut = 
                       mean(outOfCentralArea, na.rm = FALSE))
  subjectsToExclude <- filter( pOutCentralArea, pOut>(1-proportnTrialsMustFixate) )
  if (nrow(subjectsToExclude) > 0) {
    subjectsToExclude<- subjectsToExclude$subject
    cat("Excluding Ss for fixatn failure in >",100*(1-proportnTrialsMustFixate),
              "% of trials:",subjectsToExclude,'.\n',sep=' ')
    dat<- filter(dat, !(subject %in% subjectsToExclude))
  } else { 
    cat("No participants excluded for breaking fixatn in >",100*(1-proportnTrialsMustFixate),"% of trials\n",sep='')
  }
  
  datFixatnGood<- subset(dat,dat$outOfCentralArea==0)
  eyeMovementsUnknown<- subset(datWithFixatnViolatns, is.na(datWithFixatnViolatns$outOfCentralArea))
  #datNoFixatnViolatn<- dat[,dat$outOfCentralArea==0  &  !is.na(dat$outOfCentralArea)]
  cat("Excluded for not having eyetracking data:",unique(eyeMovementsUnknown$subject),".")
  pctExcludedBrokeFixatn<-round((1-nrow(datFixatnGood) / 
                                (nrow(datWithFixatnViolatns)-nrow(eyeMovementsUnknown)))*100)
  pctExcludedNoEyemoveData<-round(100*nrow(eyeMovementsUnknown)/nrow(datWithFixatnViolatns))
  cat(" Of remainder, further ",pctExcludedBrokeFixatn,"% excluded for breaking fixation.",sep='')
  dat<-datFixatnGood

}
iv= 'speed'
#need to translate offsetXYeachRing to verbal condName label
assignCondName <- function(df) {
  df$condName='nothing'
  whichSquareExp = df$exp=='circleOrSquare_twoTargets'
  df$condName[ whichSquareExp ] = df$basicShape[whichSquareExp]
  df$condName[ df$offsetXYring0=='[-10, 0]' ] = "far"
  df$condName[ df$offsetXYring0=='[10, 0]' ] = "far"
  df$condName[ df$offsetXYring0=='[-5, 0]' ] = "near"
  df$condName[ df$offsetXYring0=='[5, 0]' ] = "near"
  df$condName[ df$offsetXYring0=='[0, 0]' ] = "centered"
  df$condName[ df$offsetXYring0=='[0, 0]' ] = "centered"
  return (df)
}
dat<-assignCondName(dat)
table(dat$exp,dat$condName)
factorsEachExpForBreakdown<- list(  list(colorF='condName',colF='subject',rowF='leftOrRight'),
                                    list(colorF='condName',colF='subject',rowF='ringToQuery') )

####################analyse circleOrSquare_twoTargets ################
expThis= "circleOrSquare_twoTargets" # "offCenter"
#how specific to break down the data before fitting
factorsForBreakdownForAnalysis <- factorsEachExpForBreakdown[[2]]
#print proportion trials excluded each condition
if (!excludeFixationViolations) {
  cat("Proportion trials where each broke fixation; NOT excluding these")
  print( dplyr::summarise(group_by(dat,subject,condName),pctExcluded=mean(outOfCentralArea)) )
}
if (excludeDidntReach75pct) {
  #is there any subject who did not reach 75% for any condition? at any speed
  subjCondSpeed<- dplyr::summarise(group_by(dat, subject,condName, speed),
            correct=mean(correct))
  #determine max %corr for each subj-condition
  maxSubjCond<- dplyr::summarise(group_by(subjCondSpeed,subject,condName),
                          max=max(correct))
  badSs<- dplyr::filter(maxSubjCond, max<.75)
  badSs<- unique(badSs$subject)
  cat("Excluded for not reaching 75% in one or both conditions:",badSs)
  dat<- dplyr::filter(dat,!(subject %in% badSs))
} 
datThis<-subset(dat,exp==expThis)
datAnalyze<-datThis
#factorsForBreakdownForAnalysis[ length(factorsForBreakdownForAnalysis)+1 ]<- "exp"
if (!useQuickpsy) {
  source('analyzeMakeReadyForPlot.R') #returns fitParms, psychometrics, and function calcPctCorrThisSpeed
  source('individDataWithPsychometricCurves.R') #for plotIndividDataAndCurves()
  plotIndividDataAndCurves(expThis,datThis,psychometrics,factorsForBreakdownForAnalysis,xmin=1,xmax=2.5)
}
if (useQuickpsy) {
  datDani<-datThis  # datDani$speed = -1*datDani$speed
  tit<- paste0(expThis,"vanilla")
  #Create decreasing function to fit
  negCumNormal<-function(x,p) { cum_normal_fun(-x,p) }
  fitCondSubj <- quickpsy(datThis, speed, correct, grouping=.(condName,subject), 
                  bootstrap='none', xmin=.5, xmax=2.2,
                  fun=negCumNormal, guess=0.5, parini = c(1.5,10))
  plot1 <- plotcurves(fitCondSubj) + theme_bw()
  quartz(tit); show(plot1)

  #test whether can fit data broken down all the way including ringToQuery
  tit<-paste(expThis,"including ringQuery")
  result = tryCatch({ 
    calcThreshes = TRUE
    fit <- quickpsy(datThis, speed, correct, grouping=.(condName,subject,ringToQuery), 
                  bootstrap='none', xmin=.5, xmax=2.2, thresholds=calcThreshes,
                  fun=negCumNormal, guess=0.5, parini = c(1.5,10))
  }, error = function(e) {
    msg="Not enough data from first-years to always get non-flat curve for ringToQuery 0 and 1"
    cat(msg,"\n")
    tit <- paste0(expThis,msg)
    calcThreshes = FALSE #dont try to fit curves
    fit <- quickpsy(datThis, speed, correct, grouping=.(condName,subject,ringToQuery), 
                    bootstrap='none', xmin=.5, xmax=2.2, thresholds=calcThreshes,
                    fun=negCumNormal, guess=0.5, parini = c(1.5,10))  
  })
  plot1 <- plotcurves(fit) + theme_bw()
  quartz(tit); show(plot1)
  
  #because ringToQuery is not relevant, don't publish this graph
  tit<- paste0(expThis,"NotToPublish_ThreshesIncludingRingToQuery")
  quartz(title=tit,width=4.3,height=3.7) #create graph of thresholds
  g=ggplot(fit$thresholds, 
           aes(x=factor(condName), y=thre))   + theme_bw()
  dodgeAmt=.4
  g<-g+stat_summary(fun.data="mean_cl_boot",geom="errorbar",width=.3,conf.int=.95,
                    width=5,size=1) 
  g<-g+geom_point(  aes(x=factor(condName), y=thre, 
                        shape=factor(subject), color=factor(ringToQuery)), 
                    position=position_dodge(dodgeAmt), size =2.9   )
  g<-g+geom_line(aes(group=interaction(subject,factor(ringToQuery))),
                 position=position_dodge(width=dodgeAmt))
  show(g)
  ggsave( paste('figs/',tit,'.png',sep='') )
  
  #threshes plot to publish
  tit<- paste0(expThis,"_threshes")
  quartz(title=tit,width=4.3,height=3.7) #create graph of thresholds
  g=ggplot(fit$thresholds, 
           aes(x=condName, y=thre))   + theme_bw()
  dodgeAmt=.4
  g<-g+stat_summary(fun.data="mean_cl_boot",geom="errorbar",conf.int=.95,
                    width=.4,size=1)
  g<-g+stat_summary(fun.y=mean,geom="point",size=3) #confidence interval point at centre
  g<-g+stat_summary(fun.y=mean, geom="point",aes(color=factor(subject)),
                        position=position_dodge(dodgeAmt))
  ylims<-c(0.5,2.2)
  ylimsCurr <- ggplot_build(g)$panel$ranges[[1]]$y.range 
  if ((ylims[1] < ylimsCurr[1]) & (ylims[2] > ylimsCurr[2])) {
    g<-g+ coord_cartesian( ylim=ylims)
  }
  g<-g+xlab("condition")+ylab("threshold") #prettify
  g<-g+labs(color="subject") #prettify
  #g<-g+geom_line(aes(color=factor(subject)))
  #g<-g+geom_line(aes(group=subject))
  #g<-g+geom_line(aes(group=interaction(subject,factor(ringToQuery))),
  #               position=position_dodge(width=dodgeAmt))
  show(g)
  ggsave( paste('figs/',tit,'.png',sep='') )
}
if (!useQuickpsy) {
source("extractThreshesAndPlot.R") #provides threshes, thresh plots
}
#Compare thresholds.
#quickpsy stuff require thresholds be bootstrapped
#thresholdcomparisons(fit)
#fit <- quickpsy(datThis, speed, correct, grouping=.(condName,subject), 
#                bootstrap='parametric', xmin=.5, xmax=2.2,
#                fun=negCumNormal, guess=0.5, parini = c(1.5,10))
#one_thresholdcomparisons(fit$thresholdsbootstrap, fit$thresholds, "condName", ci=.95)

circleThreshes=fitCondSubj$thresholds %>% filter(condName=="circle")
diamondThreshes=fitCondSubj$thresholds %>% filter(condName=="diamond")
t<- t.test(circleThreshes$thre,diamondThreshes$thre,paired=TRUE)
paste0("Mean circleThresh=",round(mean(circleThreshes$thre),1),
      " diamond=",round(mean(diamondThreshes$thre),1),
      ", t(",t$parameter["df"],")=",round(t$statistic,3),", p=",round(t$p.value,3))

####################analyse offCenter #######################################
expThis= "offCenter"
factorsForBreakdownForAnalysis <- factorsEachExpForBreakdown[[1]]
datThis<-subset(dat,exp==expThis)
datThis$subject<- as.factor(datThis$subject)
#Change the ordering of the Ss so the expert ones listed first, because they participated
#in an additional condition.
#datThis$subject <- reorder(datThis$subject, c(2,5,3,1,4,6)) #why doesn't this work?
datThis$subject<- factor(datThis$subject, levels=levels(datThis$subject)[c(2,5,3,1,4,6)])

if (!useQuickpsy) {
  source('analyzeMakeReadyForPlot.R') #returns fitParms, psychometrics, and function calcPctCorrThisSpeed
  source('individDataWithPsychometricCurves.R') #for plotIndividDataAndCurves()
  plotIndividDataAndCurves(expThis,datThis,psychometrics,factorsForBreakdownForAnalysis,xmin=1,xmax=2.5)
}
if (useQuickpsy) {
  #datDani<-datThis; datDani$speed = -1*datDani$speed
  #Create decreasing function to fit
  negCumNormal<-function(x,p) { cum_normal_fun(-x,p) }
  fit <- quickpsy(datThis, speed, correct, grouping=.(condName,subject,leftOrRight),
                  xmin=.8, xmax=2.6,
                  fun=negCumNormal, guess=0.5, parini = c(1.5,10),
                  bootstrap='none')
  #Problems: participant XA has a flat function for one left condition, LO is too good.
  plotDodged<-function(fit) {
    p<-ggplot()  +
      geom_point(data = fit$averages, aes(x = speed, y = y, color = condName), 
                 position=position_dodge(width=.15)) 
    p<-p+ geom_line(data = fit$curves, 
                  aes(x = x, y = y, color = condName))
    #fit$thresholds[[color]] <- factor(fit$thresholds[[color]])
    colorForThreshes <- fit$groups[[1]]
    # get present axis limits
    axisYrange <- ggplot_build(p)$panel$ranges[[1]]$y.range
    p <- p + geom_linerange(data = fit$thresholds,
                            aes_string(x = 'thre', 
                                       ymin = axisYrange[1] - .2, #make sure extends below axis line
                                       ymax = fit$thresholds$prob, color = colorForThreshes))
    #Because threshline extended below axis limit, axis automatically scaled below it.
    #Restore it to its former values
    p <- p + coord_cartesian(ylim=axisYrange)
    return (p)
  }
 plot1=plotDodged(fit)+theme_bw() +facet_grid(leftOrRight~subject)
 quartz(title="breakDownByLeftOrRight_notForPublication",expThis); show(plot1)
 #find my code from last paper for plotting threshes?
 #plotthresholds(fit,color=condName)
 offCtrLeftRightThreshes = fit$thresholds
}
#LO's threshold for centered could not be estimated, he's too fast. 
#But point is if anything, people better for centered than for other conditions.
#Compare percent correct for left versus right
notCentered<- filter(datThis,condName!="centered") #centered condition doesnt have left vs right
leftRightSubj<-dplyr::summarise(group_by(notCentered, subject,leftOrRight),
                 corr=mean(correct))
left<- filter(leftRightSubj,leftOrRight==0)$corr
right<- filter(leftRightSubj,leftOrRight==1)$corr
t<- t.test(left,right,paired=TRUE)
paste0("Mean left=",round(mean(left),2),
       " right=",round(mean(right),2),
       ", t(",t$parameter["df"],")=",round(t$statistic,3),", p=",round(t$p.value,3))
#No sig advantage of left or right side, so collapse but need ANOVA test to justify
ANOVA
#Dont break down by left or right this time
tit<- paste0(expThis,"_psychometrics")
quartz(title=tit,width=7,height=3.) #create graph of thresholds, left vs. Right
fit <- quickpsy(datThis, speed, correct, grouping=.(condName,subject),
                xmin=.8, xmax=2.6,
                fun=negCumNormal, guess=0.5, parini = c(1.5,10),
                bootstrap='none')
offCtrThreshes <- fit$thresholds
plot2=plotDodged(fit)+theme_bw() +facet_grid(.~subject)
show(plot2)
ggsave( paste('figs/',tit,'.png',sep='') )

tit<-paste0(expThis,"_threshes")
quartz(title=tit,width=4.3,height=3.7) #create graph of thresholds
g=ggplot(offCtrThreshes, aes(x=factor(condName), y=thre, color=subject,shape=subject))   + theme_bw()
dodgeAmt=.25
g<-g+stat_summary(fun.data="mean_cl_boot",geom="errorbar",width=.3,conf.int=.95,
                  width=5,size=1,position=position_dodge(width=dodgeAmt)) 
g<-g+geom_point(  aes(x=factor(condName), y=thre), 
                  position=position_dodge(dodgeAmt), size =2.9   )
g<-g+geom_line(aes(group=subject),position=position_dodge(dodgeAmt))
#g<-g+geom_line(aes(group=interaction(subject,factor(leftOrRight)),color=factor(leftOrRight)),
#               position=position_dodge(width=dodgeAmt))
show(g)
ggsave( paste('figs/',tit,'.png',sep='') )

#PRESENTLY OLD EXPERIMENTS ANALYSED BY PRE-REPOSITORY FILES
# expName="postVSS_13targets2349objects"
# anonDataFname= paste(dataDir,expName,".Rdata",sep="") #data/postVSS_13targets2349objects.RData
# load(anonDataFname,verbose=TRUE) #returns dat
# dat$expName = expName
# colsNotInE1 = setdiff(colnames(dat),colnames(datE1))
# datE1[,colsNotInE1] = -999 #dummy value
# colsNotInThisOne = setdiff(colnames(datE1),colnames(dat))
# dat[,colsNotInThisOne] = -999 #dummy value
# dat = rbind(dat,datE1)
#
# dat$tf = dat$speed*dat$numObjects
# for (iv in c("speed","tf")) {
#   cat('Fitting data, extracting threshes, plotting with iv=',iv)
#   source('analyzeMakeReadyForPlot.R') #returns fitParms, psychometrics, and function calcPctCorrThisSpeed
#   if (iv=="speed") { #if not, don't bother
#     source('plotIndividDataWithPsychometricCurves.R')
#   }
#   #should also do it normalizing by subjects' speed limits
#   source("extractThreshesAndPlot.R") #provides threshes, thresh plots
#
#   varName=paste("threshes_",iv,"_",expName,sep='') #combine threshes
#   assign(varName,threshes)
#   save(list=varName,file=paste(dataDir,varName,".Rdata",sep='')) #e.g. threshes_tf_123targets269objects.Rdata
# }
#
# #CRT_spinzter experiment#######################################################################
# load( paste0(dataDir,"E2_CRT_spinzter.RData"),verbose=TRUE) #E2
# E2<-dat
# #For CRT data, I need to take mean across trials. Spinzter already is
# meanThreshold<-function(df) {
#   thresh<-mean(df$thresh)
#   df= data.frame(thresh)
#   return(df)
# }
# factorsPlusSubject=c("numObjects","subject","direction","ecc","device")
#
# E2threshes<- ddply(E2, factorsPlusSubject,meanThreshold) #average over trialnum,startSpeed
#
# #then plot
# tit<-"E2threshesSpeed"
# quartz(title=tit,width=2.8,height=2.9) #create graph of thresholds
# g=ggplot(E2threshes, aes(x=numObjects-1, y=thresh, color=device, shape=factor(ecc)))
# g<-g + xlab('Distractors')+ylab('threshold speed (rps)')
# dodgeAmt=0.35
# SEerrorbar<-function(x){ SEM <- sd(x) / (sqrt(length(x))); data.frame( y=mean(x), ymin=mean(x)-SEM, ymax=mean(x)+SEM ) }
# g<-g+ stat_summary(fun.data="SEerrorbar",geom="point",size=2.5,position=position_dodge(width=dodgeAmt))
# #g<-g+ stat_summary(fun.y=mean,geom="point",size=2.5,position=position_dodge(width=dodgeAmt))
# g<-g+stat_summary(fun.data="SEerrorbar",geom="errorbar",width=.25,position=position_dodge(width=dodgeAmt))
# g=g+theme_bw() #+ facet_wrap(~direction)
# g<-g+ coord_cartesian( ylim=c(1.0,2.5), xlim=c(0.6,2.4))
# g<-g+ scale_x_continuous(breaks=c(1,2))
# g<-g+ theme(axis.title.y=element_text(vjust=0.22))
# g<-g+theme(panel.grid.minor=element_blank(),panel.grid.major=element_blank())# hide all gridlines.
# show(g)
# ggsave( paste('figs/',tit,'.png',sep='') )
#
# #source ( model limits) ??
# #source analyseSlopes?
#
