#This file analyses anonymized data provided by "loadAnonymiseSaveData.R" in exp-specific directory
#Working directory is set hopefully by Rproj file to directory that it's in.
setwd(
"/Users/alexh/Documents/attention_tempresltn/multiple object tracking/newTraj/newTraj_repo/analysis"
)
dataDir="../dataAnonymized/"
expName="offCenterAndShape"
anonDataFilename = paste(dataDir,expName,".Rdata",sep="") #generated by loadAnonymiseSaveData.R
load(anonDataFilename,verbose=TRUE)  #returns dat
excludeFixationViolations = TRUE; proportnTrialsMustFixate = .6
useQuickpsy = TRUE
if (useQuickpsy) {
  library('quickpsy')
}
datWithFixatnViolatns = dat #save for possible future use
#somehow CF eyetracking data not included for offCenter
if (excludeFixationViolations) {
  bySubjExp <- dat %>% group_by(subject,exp)
  pOutCentralArea <- summarise(bySubjExp, pOut = 
                       mean(outOfCentralArea, na.rm = FALSE))
  subjectsToExclude <- filter( pOutCentralArea, pOut>(1-proportnTrialsMustFixate) )
  if (nrow(subjectsToExclude) > 0) {
    subjectsToExclude<- subjectsToExclude$subject
    cat("Excluding Ss for fixatn failure in >",100*(1-proportnTrialsMustFixate),
              "% of trials:",subjectsToExclude,'\n',sep='')
    dat<- filter(dat, !(subject %in% subjectsToExclude))
  } else { 
    cat("No participants excluded for breaking fixatn in >",100*(1-proportnTrialsMustFixate),"% of trials\n",sep='')
  }
  
  datFixatnGood<- subset(dat,dat$outOfCentralArea==0)
  eyeMovementsUnknown<- subset(datWithFixatnViolatns, is.na(datWithFixatnViolatns$outOfCentralArea))
  #datNoFixatnViolatn<- dat[,dat$outOfCentralArea==0  &  !is.na(dat$outOfCentralArea)]
  cat("Excluded for not having eyetracking data:",unique(eyeMovementsUnknown$subject))
  pctExcludedBrokeFixatn<-round((1-nrow(datFixatnGood) / 
                                (nrow(datWithFixatnViolatns)-nrow(eyeMovementsUnknown)))*100)
  pctExcludedNoEyemoveData<-round(100*nrow(eyeMovementsUnknown)/nrow(datWithFixatnViolatns))
  cat("Of remainder, further ",pctExcludedBrokeFixatn,"% excluded for breaking fixation.")
  dat<-datFixatnGood

}
iv= 'speed'
#need to translate offsetXYeachRing to verbal condName label
assignCondName <- function(df) {
  df$condName='nothing'
  whichSquareExp = df$exp=='circleOrSquare_twoTargets'
  df$condName[ whichSquareExp ] = df$basicShape[whichSquareExp]
  df$condName[ df$offsetXYring0=='[-10, 0]' ] = "far"
  df$condName[ df$offsetXYring0=='[10, 0]' ] = "far"
  df$condName[ df$offsetXYring0=='[-5, 0]' ] = "near"
  df$condName[ df$offsetXYring0=='[5, 0]' ] = "near"
  df$condName[ df$offsetXYring0=='[0, 0]' ] = "centered"
  df$condName[ df$offsetXYring0=='[0, 0]' ] = "centered"
  return (df)
}
dat<-assignCondName(dat)
table(dat$exp,dat$condName)
factorsEachExpForBreakdown<- list(  list(colorF='condName',colF='subject',rowF='leftOrRight'),
                                    list(colorF='condName',colF='subject',rowF='ringToQuery') )

####################analyse circleOrSquare_twoTargets ################
expThis= "circleOrSquare_twoTargets" # "offCenter"
#how specific to break down the data before fitting
factorsForBreakdownForAnalysis <- factorsEachExpForBreakdown[[2]]
#print proportion trials excluded each condition
if (!excludeFixationViolations) {
  ddply(dat,.(subject,condName),summarize, pctExcluded = mean(outOfCentralArea))
}
datThis<-subset(dat,exp==expThis)
datAnalyze<-datThis
#factorsForBreakdownForAnalysis[ length(factorsForBreakdownForAnalysis)+1 ]<- "exp"
if (!useQuickpsy) {
  source('analyzeMakeReadyForPlot.R') #returns fitParms, psychometrics, and function calcPctCorrThisSpeed
  source('individDataWithPsychometricCurves.R') #for plotIndividDataAndCurves()
  plotIndividDataAndCurves(expThis,datThis,psychometrics,factorsForBreakdownForAnalysis,xmin=1,xmax=2.5)
}
if (useQuickpsy) {
  datDani<-datThis  # datDani$speed = -1*datDani$speed
  tit<- paste0(expThis,"vanilla")
  #Create decreasing function to fit
  negCumNormal<-function(x,p) { cum_normal_fun(-x,p) }
  fit <- quickpsy(datThis, speed, correct, grouping=.(condName,subject), 
                  bootstrap='none', xmin=.5, xmax=2.2,
                  fun=negCumNormal, guess=0.5, parini = c(1.5,10))
  plot1 <- plotcurves(fit) + theme_bw()
  quartz(tit); show(plot1)

  #test new error
  fit <- quickpsy(datThis, speed, correct, grouping=.(condName,subject,ringToQuery), 
                  bootstrap='none', xmin=.5, xmax=2.2, thresholds=TRUE,
                  fun=negCumNormal, guess=0.5, parini = c(1.5,10))
  tit<- paste0(expThis,"not enough data from first-years to fit ringToQuery")
  fit <- quickpsy(datThis, speed, correct, grouping=.(condName,subject,ringToQuery), 
                  bootstrap='none', xmin=.5, xmax=2.2, thresholds=FALSE,
                  fun=negCumNormal, guess=0.5, parini = c(1.5,10))
  plot1 <- plotcurves(fit) + theme_bw()
  quartz(tit); show(plot1)
  
  #because ringToQuery is not relevant, don't publish this graph
  tit<- paste0(expThis,"NotToPublish_ThreshesIncludingRingToQuery")
  quartz(title=tit,width=4.3,height=3.7) #create graph of thresholds
  g=ggplot(fit$thresholds, 
           aes(x=factor(condName), y=thre))   + theme_bw()
  dodgeAmt=.4
  g<-g+stat_summary(fun.data="mean_cl_boot",geom="errorbar",width=.3,conf.int=.95,
                    width=5,size=1) 
  g<-g+geom_point(  aes(x=factor(condName), y=thre, 
                        shape=factor(subject), color=factor(ringToQuery)), 
                    position=position_dodge(dodgeAmt), size =2.9   )
  g<-g+geom_line(aes(group=interaction(subject,factor(ringToQuery))),
                 position=position_dodge(width=dodgeAmt))
  show(g)
  ggsave( paste('figs/',tit,'.png',sep='') )
  
  #threshes plot to publish
  tit<- paste0(expThis,"_threshes")
  quartz(title=tit,width=4.3,height=3.7) #create graph of thresholds
  g=ggplot(fit$thresholds, 
           aes(x=factor(condName), y=thre))   + theme_bw()
  dodgeAmt=.4
  g<-g+stat_summary(fun.data="mean_cl_boot",geom="errorbar",conf.int=.95,
                    width=.4,size=1)
  g<-g+stat_summary(fun.y=mean,geom="point",size=3) #confidence interval point at centre
  g<-g+stat_summary(fun.y=mean, geom="point",aes(color=factor(subject)),
                        position=position_dodge(dodgeAmt))
  #g<-g+geom_line(aes(color=factor(subject)))
  #g<-g+geom_line(aes(group=subject))
  #g<-g+geom_line(aes(group=interaction(subject,factor(ringToQuery))),
  #               position=position_dodge(width=dodgeAmt))
  show(g)
  ggsave( paste('figs/',tit,'.png',sep='') )
}
if (!useQuickpsy) {
source("extractThreshesAndPlot.R") #provides threshes, thresh plots
}

####################analyse offCenter ################
expThis= "offCenter"
factorsForBreakdownForAnalysis <- factorsEachExpForBreakdown[[1]]
datThis<-subset(dat,exp==expThis)
if (!useQuickpsy) {
  source('analyzeMakeReadyForPlot.R') #returns fitParms, psychometrics, and function calcPctCorrThisSpeed
  source('individDataWithPsychometricCurves.R') #for plotIndividDataAndCurves()
  plotIndividDataAndCurves(expThis,datThis,psychometrics,factorsForBreakdownForAnalysis,xmin=1,xmax=2.5)
}
if (useQuickpsy) {
  #datDani<-datThis; datDani$speed = -1*datDani$speed
  #Create decreasing function to fit
  negCumNormal<-function(x,p) { cum_normal_fun(-x,p) }
  fit <- quickpsy(datThis, speed, correct, grouping=.(condName,subject,leftOrRight),
                  xmin=.8, xmax=2.6,
                  fun=negCumNormal, guess=0.5, parini = c(1.5,10),
                  bootstrap='none')
  #Problems:
  #how to change threshold criterion
  #Need to run Lizzy again at very slow speed
  #plot1 <- plotcurves(fit)
  plotDodged<-function(fit) {
    p<-ggplot() +facet_grid(leftOrRight~subject) +
      geom_point(data = fit$averages, aes(x = speed, y = y, color = condName), 
                 position=position_dodge(width=.15)) 
    p<-p+ geom_line(data = fit$curves, 
                  aes(x = x, y = y, color = condName))
    #fit$thresholds[[color]] <- factor(fit$thresholds[[color]])
    colorForThreshes <- fit$groups[[1]]
    # get present axis limits
    axisYrange <- ggplot_build(p)$panel$ranges[[1]]$y.range
    p <- p + geom_linerange(data = fit$thresholds,
                            aes_string(x = 'thre', 
                                       ymin = axisYrange[1] - .2, #make sure extends below axis line
                                       ymax = fit$thresholds$prob, color = colorForThreshes))
    #Because threshline extended below axis limit, axis automatically scaled below it.
    #Restore it to its former values
    p <- p + coord_cartesian(ylim=axisYrange)
    return (p)
  }
 plot1=plotDodged(fit)+theme_bw()
 quartz(expThis); show(plot1)
 #find my code from last paper for plotting threshes?
 #plotthresholds(fit,color=condName)
 offCtrThreshes = fit$thresholds
}
#PLOT THRESHES for off-center
#LO's threshold for centered could not be estimated. 
#But point is if anything, people better for centered than for other conditions.
tit<- paste0(expThis,"Threshes")
quartz(title=tit,width=4.3,height=3.7) #create graph of thresholds
g=ggplot(offCtrThreshes, 
         aes(x=factor(condName), y=thre))   + theme_bw()
dodgeAmt=.25
#g<-g+stat_summary(fun.data="SEerrorbar",geom="errorbar",color="black",width=.3)
g<-g+stat_summary(fun.data="mean_cl_boot",geom="errorbar",width=.3,conf.int=.95,
                  width=5,size=1,position=position_dodge(width=dodgeAmt)) 

g<-g+geom_point(  aes(x=factor(condName), y=thre, color=factor(leftOrRight),
                      shape=factor(subject)), 
                  position=position_dodge(dodgeAmt), size =2.9   )
#g<-g+geom_line(aes(group=interaction(subject,factor(leftOrRight))),
#               position=position_dodge(width=dodgeAmt))
g<-g+geom_line(aes(group=interaction(subject,factor(leftOrRight)),color=factor(leftOrRight)),
               position=position_dodge(width=dodgeAmt))
g<-g+stat_summary(fun.data="SEerrorbar",geom="point",color="black")
g
#g<-g+ coord_cartesian( ylim=c(1.0,2.5), xlim=c(0.6,2.4))
#g<-g+ theme(axis.title.y=element_text(vjust=0.22))
show(g)
ggsave( paste('figs/',tit,'.png',sep='') )

#PRESENTLY OLD EXPERIMENTS ANALYSED BY PRE-REPOSITORY FILES
# expName="postVSS_13targets2349objects"
# anonDataFname= paste(dataDir,expName,".Rdata",sep="") #data/postVSS_13targets2349objects.RData
# load(anonDataFname,verbose=TRUE) #returns dat
# dat$expName = expName
# colsNotInE1 = setdiff(colnames(dat),colnames(datE1))
# datE1[,colsNotInE1] = -999 #dummy value
# colsNotInThisOne = setdiff(colnames(datE1),colnames(dat))
# dat[,colsNotInThisOne] = -999 #dummy value
# dat = rbind(dat,datE1)
#
# dat$tf = dat$speed*dat$numObjects
# for (iv in c("speed","tf")) {
#   cat('Fitting data, extracting threshes, plotting with iv=',iv)
#   source('analyzeMakeReadyForPlot.R') #returns fitParms, psychometrics, and function calcPctCorrThisSpeed
#   if (iv=="speed") { #if not, don't bother
#     source('plotIndividDataWithPsychometricCurves.R')
#   }
#   #should also do it normalizing by subjects' speed limits
#   source("extractThreshesAndPlot.R") #provides threshes, thresh plots
#
#   varName=paste("threshes_",iv,"_",expName,sep='') #combine threshes
#   assign(varName,threshes)
#   save(list=varName,file=paste(dataDir,varName,".Rdata",sep='')) #e.g. threshes_tf_123targets269objects.Rdata
# }
#
# #CRT_spinzter experiment#######################################################################
# load( paste0(dataDir,"E2_CRT_spinzter.RData"),verbose=TRUE) #E2
# E2<-dat
# #For CRT data, I need to take mean across trials. Spinzter already is
# meanThreshold<-function(df) {
#   thresh<-mean(df$thresh)
#   df= data.frame(thresh)
#   return(df)
# }
# factorsPlusSubject=c("numObjects","subject","direction","ecc","device")
#
# E2threshes<- ddply(E2, factorsPlusSubject,meanThreshold) #average over trialnum,startSpeed
#
# #then plot
# tit<-"E2threshesSpeed"
# quartz(title=tit,width=2.8,height=2.9) #create graph of thresholds
# g=ggplot(E2threshes, aes(x=numObjects-1, y=thresh, color=device, shape=factor(ecc)))
# g<-g + xlab('Distractors')+ylab('threshold speed (rps)')
# dodgeAmt=0.35
# SEerrorbar<-function(x){ SEM <- sd(x) / (sqrt(length(x))); data.frame( y=mean(x), ymin=mean(x)-SEM, ymax=mean(x)+SEM ) }
# g<-g+ stat_summary(fun.data="SEerrorbar",geom="point",size=2.5,position=position_dodge(width=dodgeAmt))
# #g<-g+ stat_summary(fun.y=mean,geom="point",size=2.5,position=position_dodge(width=dodgeAmt))
# g<-g+stat_summary(fun.data="SEerrorbar",geom="errorbar",width=.25,position=position_dodge(width=dodgeAmt))
# g=g+theme_bw() #+ facet_wrap(~direction)
# g<-g+ coord_cartesian( ylim=c(1.0,2.5), xlim=c(0.6,2.4))
# g<-g+ scale_x_continuous(breaks=c(1,2))
# g<-g+ theme(axis.title.y=element_text(vjust=0.22))
# g<-g+theme(panel.grid.minor=element_blank(),panel.grid.major=element_blank())# hide all gridlines.
# show(g)
# ggsave( paste('figs/',tit,'.png',sep='') )
#
# #source ( model limits) ??
# #source analyseSlopes?
#
